### ISSUE TITLE
Suggestion: Get smaller images, increase page performance

### ISSUE THREAD

**Issue by tteltrab** [matt-t-johnson/matt-t-johnson.github.io#11]
Usually want to keep your site under about 2 MB if possible. Your biggest image is https://matt-t-johnson.github.io/img/portfolio/quick-plans.png , and it definitely doesn't need to be that big. Running it through a tool like https://tinypng.com/ decreases the size significantly, and the image looks good still.
![image](https://cloud.githubusercontent.com/assets/1487463/22171338/508944ca-df59-11e6-839a-d58047776f6a.png)

**Comment by matt-t-johnson** [comment]
Compressed images
