### ISSUE TITLE
Suggestion: Change alignment of skills

### ISSUE THREAD

**Issue by tteltrab** [matt-t-johnson/matt-t-johnson.github.io#9]
![image](https://cloud.githubusercontent.com/assets/1487463/22171218/608bdad8-df57-11e6-8edb-890eb5b11e54.png)

This would probably look a little more balanced if the bottom two skills were aligned to be at 1/3 and 2/3 the width instead of 1/4 and 3/4 (more what it looks like now). Basically, if they were

Considering the amount of whitespace between sections, I think the vertical spacing could be larger as well. (you might want a bit less vertical whitespace in-between sections, everything is very spaced out.

**Comment by matt-t-johnson** [comment]
used offset classes for the horizontal spacing, increased the margin-top on the second row, and reduced the padding of each section
